package:
  name: phconvert
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
    git_url: https://github.com/Photon-HDF5/phconvert.git
    #git_tag: dev

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9
    - hdf5
    - pytables
    - mock

  run:
    - python
    - setuptools
    - numpy >=1.9
    - hdf5
    - pytables

test:
  imports:
    - phconvert

about:
  home: https://photon-hdf5.github.io/phconvert
  license: MIT
  summary: 'Reference library to convert and write Photon-HDF5 files.'
